### ISSUE TITLE
Hot to implement with Playwright

### ISSUE THREAD

**Issue by eatonjl** [dotenv-org/dotenv-vault-core#10]
I am using dotenv in Playwright and they have me put 
```
import dotenv from 'dotenv';
dotenv.config();
```
in the config file. I try to do something similar with dotenv-vault-core but I can't get it to work. What is the proper syntax for using dotenv-vault-core with Typescript "import"?

**Comment by eatonjl** [comment]
I finally got it to work by manually adding a copy of DotEnv's Vault "main.d.ts" file in the lib folder for this node module. Any way that can be added by default so anyone who adds this doesn't need to manually add it (basically, give it the same functionality as DotEnv Vault)?

**Comment by eatonjl** [comment]
@motdotla Any reason why this was closed without an answer?

**Comment by motdotla** [comment]
@eatonjl sorry about that.

Closed because this repo is deprecated. All the core logic is now first-class in dotenv - https://github.com/motdotla/dotenv

**Comment by eatonjl** [comment]
@motdotla Thank you for the clarification!
