### ISSUE TITLE
Docs incorrect for custom path?

### ISSUE THREAD

**Issue by aawalton** [dotenv-org/dotenv-vault-core#14]
The README has an example for a custom path for monorepo.

`require('dotenv-vault-core').config('apps/some-app/.env.vault')`

However, in testing this didn't work. From reading the code and testing, it looks like the correct syntax is 
`require('dotenv-vault-core').config({ path: 'apps/some-app/.env.vault' })`

```
if (options && options.path && options.path.length > 0) {
    dotenvPath = options.path
  }
```

**Comment by motdotla** [comment]
thank you. closing now. updated and fixed in `dotenv`.
